projects:
  Virtual Street:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: cs5klzgkyvg2hl7dmd553tyedm
        maxDepth: 2
extensions:
  amplify:
    version: 3
