version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'virtualstreet'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'first-run-task-definition'
          cluster-name: 'virtual-street-dev'
          service-name: 'virtual-street-dev-service'
          container-image-name-updates: 'container=virtual-street-dev,tag=${CIRCLE_SHA1}'