// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:02ffe384-7e95-426e-a0e7-fa4c14a9145b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_bExYvCnMj",
    "aws_user_pools_web_client_id": "5u11hir4bgmlkovs6ficm86sg4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ngfvculugzgmziot225dhvmi24.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AWS_IAM",
}

export default awsmobile
